# NOTE: Do not edit, file was generated by jhconvert

Name: sugar-pippy-activity
Version: 25
Release: %mkrel 1
Summary: Python programming activity for Sugar
License: GPL
Group: Graphical desktop/Other
Url: http://sugarlabs.org/

Source: http://dev.laptop.org/pub/sugar/sources/Pippy/Pippy-25.tar.bz2

Patch: sugar-pippy-activity-25-olpc-4218.patch

Requires: python-gtksourceview  
Requires: python  
Requires: sugar-toolkit >= 0.84.2

BuildRequires: gettext  
BuildRequires: libpython-devel  
BuildRequires: sugar-toolkit >= 0.84.2

BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch: noarch

%description
Teaches Python programming by providing access to Python code samples
and a fully interactive Python interpreter.
The user can type and execute simple Python expressions. For example,
it would be possible for a user to write Python statements to calculate
expressions, play sounds, or make simple text animation.
The initial build ships with about twenty short Python examples covering
various aspects of the language.

%prep
%setup -q -n Pippy-25
%patch -p1

%build

rm -f MANIFEST
python setup.py build

%install
rm -rf %{buildroot}
python setup.py install --prefix=%{buildroot}/%{_prefix}
find %{buildroot} -name '*.py.orig' -print0 | xargs -0 rm -f
%ifarch x86_64
rm -rf {buildroot}/%_datadir/sugar/activities/Pippy.activity/library/pippy/physics/box2d/box2d_linux32
%else
rm -rf %{buildroot}/%{_datadir}/sugar/activities/Pippy.activity/library/pippy/physics/box2d/box2d_linux64
%endif
%find_lang org.laptop.Pippy

%clean
rm -rf %{buildroot}

%files -f org.laptop.Pippy.lang
%defattr(-,root,root,-)
%{_datadir}/sugar/activities/*
%doc NEWS

